version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo:mongo
  mongo:
    image: mongo
    volumes_from:
      - mongodata
    ports:
      - "27017:27017"
  mongodata:
    image: tianon/true
    volumes:
      - /data/db