version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes_from:
      - datastore
  mongo:
    image: mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"
  datastore:
    image: tianon/true
    volumes:
      - /datavolume